= go-dicom
David Gamba, https://github.com/DavidGamba
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Golang based implementation of the DICOM standard.

== Scripts

This repository holds different tools I use when working with different PACS servers.

link:dcmdump[]::
Golang based DICOM file Metadata dump.
+
* Current version assumes explicit VR for all fields (except of course for SQ items).
* Missing private tags.
Marked as MISSING in output and they generate an error to `os.Stderr`
* Missing handling for VM.
Backlash separator shown in value.

link:query-retrieve[]:: Wrapper around dcm4chee's `findscu` and `getscu`.
It allows to find/get all studies for a patient or all patients in the PACS.
+
* It generates json output that can list each instance (tries to, haven't fully done proper json yet) to verify that the contents of what was retrieved match the elements in the archive.
* Since it is doing a call to findscu or getscu per instance (or series) instead or reusing a single association, it is very slow.

link:qr[]:: DICOM Q/R playground.
+
This dir is mostly a playground to better understand the DICOM Q/R standard.
Nothing useful here.

== LICENSE

This file is part of go-dicom.

Copyright (C) 2016  David Gamba Rios

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
